/**
 * events.js
 *
 * Loads Copenhagen rave events from ra-events.json (generated by
 * fetch-ra-events.py) and renders them.
 *
 * To refresh event data:
 *   python3 fetch-ra-events.py
 */

// ─── State ────────────────────────────────────────────────────────────────────

let allEvents = [];
let activeTile = null;
let showingFavourites = false;

// ─── Favourites (localStorage) ───────────────────────────────────────────────

const FAV_KEY = "ravely-favourites";

function getFavourites() {
  try { return new Set(JSON.parse(localStorage.getItem(FAV_KEY)) || []); }
  catch { return new Set(); }
}

function toggleFavourite(id) {
  const favs = getFavourites();
  favs.has(id) ? favs.delete(id) : favs.add(id);
  localStorage.setItem(FAV_KEY, JSON.stringify([...favs]));
  return favs.has(id);
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function isUpcoming(dateStr) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return new Date(dateStr) >= today;
}

function shortDate(dateStr) {
  const d = new Date(dateStr);
  return d.toLocaleDateString("en-DK", {
    weekday: "short",
    day: "numeric",
    month: "short",
  });
}

// ─── Event Row ───────────────────────────────────────────────────────────────

function gcalDateTime(dateStr, timeStr, offsetDays = 0) {
  const [y, m, d] = dateStr.split("-").map(Number);
  const date = new Date(y, m - 1, d + offsetDays);
  const pad = (n) => String(n).padStart(2, "0");
  const datepart = `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}`;
  if (!timeStr) return datepart;
  const [hh, mm] = timeStr.split(":");
  return `${datepart}T${hh}${mm}00`;
}

function openGoogleCalendar(event) {
  const startH = event.startTime ? parseInt(event.startTime) : 20;
  const endH   = event.endTime   ? parseInt(event.endTime)   : startH + 2;
  const endOffsetDays = event.endTime && endH < startH ? 1 : 0;

  const dtstart = gcalDateTime(event.date, event.startTime || "20:00");
  const dtend   = gcalDateTime(event.date, event.endTime || "", endOffsetDays) ||
                  gcalDateTime(event.date, "", 1);

  const params = new URLSearchParams({
    action:   "TEMPLATE",
    text:     event.title,
    dates:    `${dtstart}/${dtend}`,
    location: event.venue,
    details:  `Tickets & info: ${event.tickets}`,
  });

  window.open(`https://calendar.google.com/calendar/render?${params}`, "_blank", "noopener,noreferrer");
}

function buildRow(event) {
  const upcoming = isUpcoming(event.date);

  const row = document.createElement("a");
  row.className = `event-row${upcoming ? " upcoming" : ""}`;
  row.href = event.tickets;
  row.target = "_blank";
  row.rel = "noopener noreferrer";

  const dateEl = document.createElement("div");
  dateEl.className = "event-date";

  const dateTextEl = document.createElement("span");
  dateTextEl.className = "event-date-text";
  dateTextEl.textContent = shortDate(event.date);
  dateEl.append(dateTextEl);

  if (event.startTime) {
    const timeEl = document.createElement("span");
    timeEl.className = "event-time";
    const timeText = event.endTime
      ? `${event.startTime} – ${event.endTime}`
      : event.startTime;
    timeEl.textContent = timeText;
    dateEl.append(timeEl);
  }

  const infoEl = document.createElement("div");
  infoEl.className = "event-info";

  const titleEl = document.createElement("span");
  titleEl.className = "event-title";
  titleEl.textContent = event.title;

  const venueEl = document.createElement("span");
  venueEl.className = "event-venue";
  venueEl.textContent = event.venue;

  infoEl.append(titleEl, venueEl);

  if (event.soldOut) {
    const tagEl = document.createElement("span");
    tagEl.className = "tag sold-out";
    tagEl.textContent = "Sold out";
    row.append(dateEl, infoEl, tagEl);
  } else if (upcoming) {
    const calBtn = document.createElement("button");
    calBtn.className = "cal-add-btn";
    calBtn.type = "button";
    calBtn.title = "Add to Google Calendar";
    calBtn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/><line x1="12" y1="14" x2="12" y2="18"/><line x1="10" y1="16" x2="14" y2="16"/></svg>`;
    calBtn.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      openGoogleCalendar(event);
    });
    row.append(dateEl, infoEl, calBtn);
  } else {
    row.append(dateEl, infoEl);
  }

  // Heart button — all events
  const favBtn = document.createElement("button");
  favBtn.className = "fav-btn";
  favBtn.type = "button";
  favBtn.title = "Save to favourites";
  const isFav = getFavourites().has(event.id);
  favBtn.classList.toggle("active", isFav);
  favBtn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>`;
  favBtn.addEventListener("click", (e) => {
    e.preventDefault();
    e.stopPropagation();
    const nowFav = toggleFavourite(event.id);
    favBtn.classList.toggle("active", nowFav);
    if (showingFavourites) renderFavourites();
  });
  row.append(favBtn);

  return row;
}

// ─── Month Calendar ─────────────────────────────────────────────────────────

const MONTH_NAMES = [
  "January","February","March","April","May","June",
  "July","August","September","October","November","December",
];

function renderMonth(monthIndex) {
  const container = document.getElementById("ra-events");
  const emptyMsg  = document.getElementById("ra-empty");
  const heading   = document.getElementById("month-heading");
  if (!container) return;

  container.innerHTML = "";

  const year = new Date().getFullYear();
  const filtered = allEvents
    .filter((ev) => {
      const d = new Date(ev.date);
      return d.getFullYear() === year && d.getMonth() === monthIndex;
    })
    .sort((a, b) => new Date(a.date) - new Date(b.date));

  if (heading) heading.textContent = MONTH_NAMES[monthIndex];

  if (filtered.length === 0) {
    container.classList.add("hidden");
    if (emptyMsg) {
      emptyMsg.textContent = `No events in ${MONTH_NAMES[monthIndex]}.`;
      emptyMsg.classList.remove("hidden");
    }
    return;
  }

  container.classList.remove("hidden");
  if (emptyMsg) emptyMsg.classList.add("hidden");

  const currentMonth = new Date().getMonth();
  const isFullyPastMonth = monthIndex < currentMonth;

  const upcoming = filtered.filter((ev) => isUpcoming(ev.date));
  const past     = filtered.filter((ev) => !isUpcoming(ev.date));

  // Render past events first so chronological order is top→bottom
  if (past.length > 0) {
    const toggle = document.createElement("button");
    toggle.className = "past-toggle";
    toggle.type = "button";
    toggle.dataset.open = String(isFullyPastMonth);
    toggle.innerHTML = isFullyPastMonth
      ? `<span class="past-toggle-label">Hide past events</span><span class="past-toggle-icon">↑</span>`
      : `<span class="past-toggle-label">Show ${past.length} past event${past.length === 1 ? "" : "s"}</span><span class="past-toggle-icon">↓</span>`;

    const pastList = document.createElement("div");
    pastList.className = `events-list past-list${isFullyPastMonth ? "" : " hidden"}`;
    past.forEach((ev) => pastList.append(buildRow(ev)));

    toggle.addEventListener("click", () => {
      const isOpen = toggle.dataset.open === "true";
      toggle.dataset.open = String(!isOpen);
      pastList.classList.toggle("hidden", isOpen);
      toggle.querySelector(".past-toggle-label").textContent = isOpen
        ? `Show ${past.length} past event${past.length === 1 ? "" : "s"}`
        : `Hide past events`;
      toggle.querySelector(".past-toggle-icon").textContent = isOpen ? "↓" : "↑";
    });

    container.append(toggle, pastList);
  }

  // Render upcoming events below
  if (upcoming.length > 0) {
    const upcomingList = document.createElement("div");
    upcomingList.className = "events-list";
    upcoming.forEach((ev) => upcomingList.append(buildRow(ev)));
    container.append(upcomingList);
  }
}

// ─── Favourites view ─────────────────────────────────────────────────────────

function renderFavourites() {
  const container = document.getElementById("ra-events");
  const heading   = document.getElementById("month-heading");
  const emptyMsg  = document.getElementById("ra-empty");
  if (!container) return;

  container.innerHTML = "";
  if (heading) heading.textContent = "Favourites";

  const favs = getFavourites();
  const favEvents = allEvents
    .filter((ev) => favs.has(ev.id))
    .sort((a, b) => new Date(a.date) - new Date(b.date));

  if (favEvents.length === 0) {
    container.classList.add("hidden");
    if (emptyMsg) {
      emptyMsg.textContent = "No favourites yet — tap ♥ on any event to save it.";
      emptyMsg.classList.remove("hidden");
    }
    return;
  }

  container.classList.remove("hidden");
  if (emptyMsg) emptyMsg.classList.add("hidden");

  const list = document.createElement("div");
  list.className = "events-list";
  favEvents.forEach((ev) => list.append(buildRow(ev)));
  container.append(list);
}

function buildMonthCalendar() {
  const calendar = document.getElementById("month-calendar");
  if (!calendar) return;
  calendar.innerHTML = "";

  const now = new Date();
  const year = now.getFullYear();
  const currentMonth = now.getMonth();

  const yearEl = document.getElementById("cal-year");
  if (yearEl) yearEl.textContent = year;

  const counts = Array(12).fill(0);
  allEvents.forEach((ev) => {
    const d = new Date(ev.date);
    if (d.getFullYear() === year) counts[d.getMonth()]++;
  });

  const names = ["Jan","Feb","Mar","Apr","May","Jun",
                  "Jul","Aug","Sep","Oct","Nov","Dec"];

  names.forEach((name, i) => {
    const tile = document.createElement("button");
    tile.className = "cal-month";
    tile.type = "button";
    if (i === currentMonth) tile.classList.add("current");
    if (i < currentMonth) tile.classList.add("past");
    if (counts[i] > 0) tile.classList.add("has-events");

    const nameEl = document.createElement("span");
    nameEl.className = "cal-month-name";
    nameEl.textContent = name;

    const countEl = document.createElement("span");
    countEl.className = "cal-month-count";
    countEl.textContent = counts[i] > 0 ? counts[i] : "–";

    const unitEl = document.createElement("span");
    unitEl.className = "cal-month-unit";
    unitEl.textContent = "events";

    tile.append(nameEl, countEl, unitEl);

    tile.addEventListener("click", () => {
      if (activeTile) activeTile.classList.remove("selected");
      tile.classList.add("selected");
      activeTile = tile;
      renderMonth(i);
    });

    if (i === currentMonth) {
      tile.classList.add("selected");
      activeTile = tile;
    }

    calendar.append(tile);
  });
}

// ─── Load & Render ───────────────────────────────────────────────────────────

async function init() {
  const container = document.getElementById("ra-events");
  const emptyMsg  = document.getElementById("ra-empty");

  let data;
  try {
    const res = await fetch("ra-events.json");
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    data = await res.json();
  } catch (err) {
    console.error("Could not load ra-events.json:", err);
    if (container) container.classList.add("hidden");
    if (emptyMsg) {
      emptyMsg.textContent =
        "Could not load events — run: python3 fetch-ra-events.py";
      emptyMsg.classList.remove("hidden");
    }
    return;
  }

  allEvents = data.events || [];

  buildMonthCalendar();
  renderMonth(new Date().getMonth());

  // Favourites filter button
  const favFilterBtn = document.getElementById("fav-filter-btn");
  if (favFilterBtn) {
    favFilterBtn.addEventListener("click", () => {
      showingFavourites = !showingFavourites;
      favFilterBtn.classList.toggle("active", showingFavourites);
      if (activeTile) activeTile.classList.toggle("dimmed", showingFavourites);
      if (showingFavourites) {
        renderFavourites();
      } else {
        const currentMonthIndex = activeTile
          ? [...activeTile.closest(".month-calendar").children].indexOf(activeTile)
          : new Date().getMonth();
        renderMonth(currentMonthIndex);
      }
    });
  }

  // Footer: show when data was last fetched from RA
  const el = document.getElementById("last-updated");
  if (el && data.fetched) {
    const d = new Date(data.fetched);
    el.textContent = d.toLocaleDateString("en-DK", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });
  }
}

document.addEventListener("DOMContentLoaded", init);
