/**
 * events.js
 *
 * Loads Copenhagen rave events from ra-events.json (generated by
 * fetch-ra-events.py) and renders them.
 *
 * To refresh event data:
 *   python3 fetch-ra-events.py
 */

// ─── State ────────────────────────────────────────────────────────────────────

let allEvents = [];
let activeTile = null;
let searchTimeout = null;

// ─── Helpers ─────────────────────────────────────────────────────────────────

function isUpcoming(dateStr) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return new Date(dateStr) >= today;
}

function shortDate(dateStr) {
  const d = new Date(dateStr);
  return d.toLocaleDateString("en-DK", {
    weekday: "short",
    day: "numeric",
    month: "short",
  });
}

// ─── Event Row ───────────────────────────────────────────────────────────────

function gcalDateTime(dateStr, timeStr, offsetDays = 0) {
  const [y, m, d] = dateStr.split("-").map(Number);
  const date = new Date(y, m - 1, d + offsetDays);
  const pad = (n) => String(n).padStart(2, "0");
  const datepart = `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}`;
  if (!timeStr) return datepart;
  const [hh, mm] = timeStr.split(":");
  return `${datepart}T${hh}${mm}00`;
}

function openGoogleCalendar(event) {
  const startH = event.startTime ? parseInt(event.startTime) : 20;
  const endH   = event.endTime   ? parseInt(event.endTime)   : startH + 2;
  const endOffsetDays = event.endTime && endH < startH ? 1 : 0;

  const dtstart = gcalDateTime(event.date, event.startTime || "20:00");
  const dtend   = gcalDateTime(event.date, event.endTime || "", endOffsetDays) ||
                  gcalDateTime(event.date, "", 1);

  const params = new URLSearchParams({
    action:   "TEMPLATE",
    text:     event.title,
    dates:    `${dtstart}/${dtend}`,
    location: event.venue,
    details:  `Tickets & info: ${event.tickets}`,
  });

  window.open(`https://calendar.google.com/calendar/render?${params}`, "_blank", "noopener,noreferrer");
}

function buildRow(event) {
  const upcoming = isUpcoming(event.date);

  const row = document.createElement("a");
  row.className = `event-row${upcoming ? " upcoming" : ""}`;
  row.href = `event.html?id=${encodeURIComponent(event.id)}`;
  row.target = "_self";
  row.addEventListener("click", () => {
    sessionStorage.setItem("ravely-scroll", String(window.scrollY));
  });

  const dateEl = document.createElement("div");
  dateEl.className = "event-date";

  const dateTextEl = document.createElement("span");
  dateTextEl.className = "event-date-text";
  dateTextEl.textContent = shortDate(event.date);
  dateEl.append(dateTextEl);

  if (event.startTime) {
    const timeEl = document.createElement("span");
    timeEl.className = "event-time";
    const timeText = event.endTime
      ? `${event.startTime} – ${event.endTime}`
      : event.startTime;
    timeEl.textContent = timeText;
    dateEl.append(timeEl);
  }

  const infoEl = document.createElement("div");
  infoEl.className = "event-info";

  const titleEl = document.createElement("span");
  titleEl.className = "event-title";
  titleEl.textContent = event.title;

  const venueEl = document.createElement("span");
  venueEl.className = "event-venue";
  venueEl.textContent = event.venue;

  infoEl.append(titleEl, venueEl);

  const fbUrl = (event.promotionalLinks || []).find(
    (l) => l.url && (l.url.includes("facebook.com") || l.url.includes("fb.me"))
  )?.url;

  const fbSlot = fbUrl ? (() => {
    const btn = document.createElement("button");
    btn.className = "fb-link-btn";
    btn.type = "button";
    btn.title = "Open Facebook event";
    btn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="6 2 12 20" fill="currentColor" aria-hidden="true"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/></svg>`;
    btn.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      window.open(fbUrl, "_blank", "noopener,noreferrer");
    });
    return btn;
  })() : (() => {
    const ph = document.createElement("span");
    ph.className = "fb-placeholder";
    return ph;
  })();

  // FB slot first, then cal slot
  row.append(dateEl, infoEl, fbSlot);

  if (event.soldOut) {
    const tagEl = document.createElement("span");
    tagEl.className = "tag sold-out";
    tagEl.textContent = "Sold out";
    row.append(tagEl);
  } else if (upcoming) {
    const calBtn = document.createElement("button");
    calBtn.className = "cal-add-btn";
    calBtn.type = "button";
    calBtn.title = "Add to Google Calendar";
    calBtn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/><line x1="12" y1="14" x2="12" y2="18"/><line x1="10" y1="16" x2="14" y2="16"/></svg>`;
    calBtn.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      openGoogleCalendar(event);
    });
    row.append(calBtn);
  } else {
    const calPh = document.createElement("span");
    calPh.className = "cal-placeholder";
    row.append(calPh);
  }

  return row;
}

// ─── Search ──────────────────────────────────────────────────────────────────

function renderSearch(query) {
  const container  = document.getElementById("ra-events");
  const emptyMsg   = document.getElementById("ra-empty");
  const calWrapper = document.getElementById("cal-wrapper");
  const heading    = document.getElementById("month-heading");
  if (!container) return;

  const q = query.trim().toLowerCase();

  if (q.length < 3) {
    // Restore month view
    if (calWrapper) calWrapper.classList.remove("hidden");
    renderMonth(activeTile
      ? Array.from(document.querySelectorAll(".cal-month")).indexOf(activeTile)
      : new Date().getMonth());
    return;
  }

  // Hide month calendar while searching
  if (calWrapper) calWrapper.classList.add("hidden");
  if (heading) heading.textContent = `Results for "${query.trim()}"`;

  const results = allEvents.filter((ev) => {
    if (!isUpcoming(ev.date)) return false;
    const haystack = [
      ev.title,
      ev.venue,
      ...(ev.lineup || []),
      ev.description || "",
    ].join(" ").toLowerCase();
    return haystack.includes(q);
  });

  container.innerHTML = "";

  if (results.length === 0) {
    container.classList.add("hidden");
    if (emptyMsg) {
      emptyMsg.textContent = `No events found for "${query.trim()}".`;
      emptyMsg.classList.remove("hidden");
    }
    return;
  }

  container.classList.remove("hidden");
  if (emptyMsg) emptyMsg.classList.add("hidden");

  const list = document.createElement("div");
  list.className = "events-list";
  results.forEach((ev) => list.append(buildRow(ev)));
  container.append(list);
}

// ─── Month Calendar ─────────────────────────────────────────────────────────

const MONTH_NAMES = [
  "January","February","March","April","May","June",
  "July","August","September","October","November","December",
];

function renderMonth(monthIndex) {
  const container = document.getElementById("ra-events");
  const emptyMsg  = document.getElementById("ra-empty");
  const heading   = document.getElementById("month-heading");
  if (!container) return;

  container.innerHTML = "";

  const year = new Date().getFullYear();
  const filtered = allEvents
    .filter((ev) => {
      const d = new Date(ev.date);
      return d.getFullYear() === year && d.getMonth() === monthIndex;
    })
    .sort((a, b) => new Date(a.date) - new Date(b.date));

  if (heading) heading.textContent = MONTH_NAMES[monthIndex];

  if (filtered.length === 0) {
    container.classList.add("hidden");
    if (emptyMsg) {
      emptyMsg.textContent = `No events in ${MONTH_NAMES[monthIndex]}.`;
      emptyMsg.classList.remove("hidden");
    }
    return;
  }

  container.classList.remove("hidden");
  if (emptyMsg) emptyMsg.classList.add("hidden");

  const currentMonth = new Date().getMonth();
  const isFullyPastMonth = monthIndex < currentMonth;

  const upcoming = filtered.filter((ev) => isUpcoming(ev.date));
  const past     = filtered.filter((ev) => !isUpcoming(ev.date));

  // Render past events first so chronological order is top→bottom
  if (past.length > 0) {
    const toggle = document.createElement("button");
    toggle.className = "past-toggle";
    toggle.type = "button";
    toggle.dataset.open = String(isFullyPastMonth);
    toggle.innerHTML = isFullyPastMonth
      ? `<span class="past-toggle-label">Hide past events</span><span class="past-toggle-icon">↑</span>`
      : `<span class="past-toggle-label">Show ${past.length} past event${past.length === 1 ? "" : "s"}</span><span class="past-toggle-icon">↓</span>`;

    const pastList = document.createElement("div");
    pastList.className = `events-list past-list${isFullyPastMonth ? "" : " hidden"}`;
    past.forEach((ev) => pastList.append(buildRow(ev)));

    toggle.addEventListener("click", () => {
      const isOpen = toggle.dataset.open === "true";
      toggle.dataset.open = String(!isOpen);
      pastList.classList.toggle("hidden", isOpen);
      toggle.querySelector(".past-toggle-label").textContent = isOpen
        ? `Show ${past.length} past event${past.length === 1 ? "" : "s"}`
        : `Hide past events`;
      toggle.querySelector(".past-toggle-icon").textContent = isOpen ? "↓" : "↑";
    });

    container.append(toggle, pastList);
  }

  // Render upcoming events below
  if (upcoming.length > 0) {
    const upcomingList = document.createElement("div");
    upcomingList.className = "events-list";
    upcoming.forEach((ev) => upcomingList.append(buildRow(ev)));
    container.append(upcomingList);
  }
}

function buildMonthCalendar() {
  const calendar = document.getElementById("month-calendar");
  if (!calendar) return;
  calendar.innerHTML = "";

  const now = new Date();
  const year = now.getFullYear();
  const currentMonth = now.getMonth();

  const yearEl = document.getElementById("cal-year");
  if (yearEl) yearEl.textContent = year;

  const counts = Array(12).fill(0);
  allEvents.forEach((ev) => {
    const d = new Date(ev.date);
    if (d.getFullYear() === year) counts[d.getMonth()]++;
  });

  const names = ["Jan","Feb","Mar","Apr","May","Jun",
                  "Jul","Aug","Sep","Oct","Nov","Dec"];

  names.forEach((name, i) => {
    const tile = document.createElement("button");
    tile.className = "cal-month";
    tile.type = "button";
    if (i === currentMonth) tile.classList.add("current");
    if (i < currentMonth) tile.classList.add("past");
    if (counts[i] > 0) tile.classList.add("has-events");

    const nameEl = document.createElement("span");
    nameEl.className = "cal-month-name";
    nameEl.textContent = name;

    const countEl = document.createElement("span");
    countEl.className = "cal-month-count";
    countEl.textContent = counts[i] > 0 ? counts[i] : "–";

    const unitEl = document.createElement("span");
    unitEl.className = "cal-month-unit";
    unitEl.textContent = "events";

    tile.append(nameEl, countEl, unitEl);

    tile.addEventListener("click", () => {
      if (activeTile) activeTile.classList.remove("selected");
      tile.classList.add("selected");
      activeTile = tile;
      renderMonth(i);
    });

    if (i === currentMonth) {
      tile.classList.add("selected");
      activeTile = tile;
    }

    calendar.append(tile);
  });
}

// ─── Load & Render ───────────────────────────────────────────────────────────

async function init() {
  const container = document.getElementById("ra-events");
  const emptyMsg  = document.getElementById("ra-empty");

  let data;
  try {
    const res = await fetch("ra-events.json");
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    data = await res.json();
  } catch (err) {
    console.error("Could not load ra-events.json:", err);
    if (container) container.classList.add("hidden");
    if (emptyMsg) {
      emptyMsg.textContent =
        "Could not load events — run: python3 fetch-ra-events.py";
      emptyMsg.classList.remove("hidden");
    }
    return;
  }

  allEvents = data.events || [];

  buildMonthCalendar();
  renderMonth(new Date().getMonth());

  // Search
  const searchInput = document.getElementById("event-search");
  if (searchInput) {
    searchInput.addEventListener("input", () => {
      clearTimeout(searchTimeout);
      searchTimeout = setTimeout(() => renderSearch(searchInput.value), 200);
    });
  }

  // Restore scroll position if returning from a detail page
  const savedScroll = sessionStorage.getItem("ravely-scroll");
  if (savedScroll !== null) {
    requestAnimationFrame(() => window.scrollTo(0, parseInt(savedScroll, 10)));
    sessionStorage.removeItem("ravely-scroll");
  }

  // Footer: show when data was last fetched from RA
  const el = document.getElementById("last-updated");
  if (el && data.fetched) {
    const d = new Date(data.fetched);
    el.textContent = d.toLocaleDateString("en-DK", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });
  }
}

document.addEventListener("DOMContentLoaded", init);
