/**
 * events.js
 *
 * Loads Copenhagen rave events from ra-events.json (generated by
 * fetch-ra-events.py) and renders them.
 *
 * To refresh event data:
 *   python3 fetch-ra-events.py
 */

// ─── State ────────────────────────────────────────────────────────────────────

let allEvents = [];
let activeTile = null;

// ─── Helpers ─────────────────────────────────────────────────────────────────

function isUpcoming(dateStr) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return new Date(dateStr) >= today;
}

function shortDate(dateStr) {
  const d = new Date(dateStr);
  return d.toLocaleDateString("en-DK", {
    weekday: "short",
    day: "numeric",
    month: "short",
  });
}

// ─── Event Row ───────────────────────────────────────────────────────────────

function buildRow(event) {
  const upcoming = isUpcoming(event.date);

  const row = document.createElement("a");
  row.className = `event-row${upcoming ? " upcoming" : ""}`;
  row.href = event.tickets;
  row.target = "_blank";
  row.rel = "noopener noreferrer";

  const dateEl = document.createElement("span");
  dateEl.className = "event-date";
  dateEl.textContent = shortDate(event.date);

  const infoEl = document.createElement("div");
  infoEl.className = "event-info";

  const titleEl = document.createElement("span");
  titleEl.className = "event-title";
  titleEl.textContent = event.title;

  const venueEl = document.createElement("span");
  venueEl.className = "event-venue";
  venueEl.textContent = event.venue;

  infoEl.append(titleEl, venueEl);

  const tagEl = document.createElement("span");
  if (event.soldOut) {
    tagEl.className = "tag sold-out";
    tagEl.textContent = "Sold out";
  } else if (upcoming) {
    tagEl.className = "tag tickets";
    tagEl.textContent = "RA ↗";
  } else {
    tagEl.className = "tag";
    tagEl.textContent = "Past";
  }

  row.append(dateEl, infoEl, tagEl);
  return row;
}

// ─── Month Calendar ─────────────────────────────────────────────────────────

const MONTH_NAMES = [
  "January","February","March","April","May","June",
  "July","August","September","October","November","December",
];

function renderMonth(monthIndex) {
  const container = document.getElementById("ra-events");
  const emptyMsg  = document.getElementById("ra-empty");
  const heading   = document.getElementById("month-heading");
  if (!container) return;

  container.innerHTML = "";

  const year = new Date().getFullYear();
  const filtered = allEvents
    .filter((ev) => {
      const d = new Date(ev.date);
      return d.getFullYear() === year && d.getMonth() === monthIndex;
    })
    .sort((a, b) => new Date(a.date) - new Date(b.date));

  if (heading) heading.textContent = MONTH_NAMES[monthIndex];

  if (filtered.length === 0) {
    container.classList.add("hidden");
    if (emptyMsg) {
      emptyMsg.textContent = `No events in ${MONTH_NAMES[monthIndex]}.`;
      emptyMsg.classList.remove("hidden");
    }
  } else {
    container.classList.remove("hidden");
    if (emptyMsg) emptyMsg.classList.add("hidden");
    filtered.forEach((ev) => container.append(buildRow(ev)));
  }
}

function buildMonthCalendar() {
  const calendar = document.getElementById("month-calendar");
  if (!calendar) return;
  calendar.innerHTML = "";

  const now = new Date();
  const year = now.getFullYear();
  const currentMonth = now.getMonth();

  const yearEl = document.getElementById("cal-year");
  if (yearEl) yearEl.textContent = year;

  const counts = Array(12).fill(0);
  allEvents.forEach((ev) => {
    const d = new Date(ev.date);
    if (d.getFullYear() === year) counts[d.getMonth()]++;
  });

  const names = ["Jan","Feb","Mar","Apr","May","Jun",
                  "Jul","Aug","Sep","Oct","Nov","Dec"];

  names.forEach((name, i) => {
    const tile = document.createElement("button");
    tile.className = "cal-month";
    tile.type = "button";
    if (i === currentMonth) tile.classList.add("current");
    if (counts[i] > 0) tile.classList.add("has-events");

    const nameEl = document.createElement("span");
    nameEl.className = "cal-month-name";
    nameEl.textContent = name;

    const countEl = document.createElement("span");
    countEl.className = "cal-month-count";
    countEl.textContent = counts[i] > 0 ? counts[i] : "–";

    const unitEl = document.createElement("span");
    unitEl.className = "cal-month-unit";
    unitEl.textContent = "events";

    tile.append(nameEl, countEl, unitEl);

    tile.addEventListener("click", () => {
      if (activeTile) activeTile.classList.remove("selected");
      tile.classList.add("selected");
      activeTile = tile;
      renderMonth(i);
    });

    if (i === currentMonth) {
      tile.classList.add("selected");
      activeTile = tile;
    }

    calendar.append(tile);
  });
}

// ─── Load & Render ───────────────────────────────────────────────────────────

async function init() {
  const container = document.getElementById("ra-events");
  const emptyMsg  = document.getElementById("ra-empty");

  let data;
  try {
    const res = await fetch("ra-events.json");
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    data = await res.json();
  } catch (err) {
    console.error("Could not load ra-events.json:", err);
    if (container) container.classList.add("hidden");
    if (emptyMsg) {
      emptyMsg.textContent =
        "Could not load events — run: python3 fetch-ra-events.py";
      emptyMsg.classList.remove("hidden");
    }
    return;
  }

  allEvents = data.events || [];

  buildMonthCalendar();
  renderMonth(new Date().getMonth());

  // Footer: show when data was last fetched from RA
  const el = document.getElementById("last-updated");
  if (el && data.fetched) {
    const d = new Date(data.fetched);
    el.textContent = d.toLocaleDateString("en-DK", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });
  }
}

document.addEventListener("DOMContentLoaded", init);
